"""add_story

Revision ID: c8c8e721719a
Revises: 89ada066a9e9
Create Date: 2019-12-24 17:32:46.761300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c8e721719a'
down_revision = '89ada066a9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('murmur_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('murmur_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=65536), nullable=False),
    sa.ForeignKeyConstraint(['murmur_id'], ['murmur.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('murmur_story')
    # ### end Alembic commands ###
